---
title: "About"
author: "Paige"
date: "9/7/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Education

  * Appalachian State University
    + I started my undergraduate degree in Mathematics for Life Sciences in the Fall of 2015. I am currently in my third           year at Appalachian and plan to graduate in the Spring of 2019. I will be graduating with a B.S. in Mathematics and          minors in Statistics, Computer Science, and Biology. I currently working on a really interesting research project.           After I graduate from Appalachain State I plan to continue my education and go to graduate school for Data Science. 

#Hobbies

 * Contra Dancing
    + When I first started college I joined the Applachian Heritage Council which introduced me to old-time dancing. Soon          after I   joined the council I began dancing in the Swing Dance Club and the Blues Unified Dance Scene of Boone. I           prefer contra dancing over any other style of dance and regularly attend dance weekends and monthly contra dances in         areas I am at. To learn more about my Boone, NC contra dancing scene and to learn about what contra dancing is visit         the [link](http://www.boonecountrydancers.org/).
 
 * Running
    + My dad first got me into running, since he is also training for the next race. I have always used running as a type of       "self therapy" and stress reliever. I have participated in many 5k's, 10k's, and a half marathon. 
    
 * Climbing
    + Over the summer of 2017 my roommate and I began climbing at a local climbing wall in Boone called Center 45. It has          been  such great social activity as well as an individual challenge. The problems only stay up for a week or two and         if you haven't been able to complete one you have been working on during that time then you don't get to dwell on it         but you have a new challenge.
    
 * Reading
    + I have never been much of a reader until recently. Over the summer I was reading _The Girl with the Dragon Tattoo_ by        Stieg Larsson and I could not put the book down which was the case for all of the books in the series. I enojy reading       fiction, mysteries, and fantasies but also books that will cause me to think or inspire me to improve myself.
